import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight, Check, Network } from 'lucide-react';
import { services } from '@/lib/content';
import { CTA } from '@/components/footer';
export const dynamicParams = false;
export function generateStaticParams() { return [...services.map(s => ({ slug:s.slug })), {slug:'nosotros'}]; }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> { const {slug} = await params; const s = services.find(s => s.slug === slug); return { title:s?.name ?? 'Nosotros', description:s?.description ?? 'Conoce la visión y la forma de trabajar de DataLink Tech Corp.', alternates:{canonical:`/${slug}/`} }; }
export default async function Detail({params}:{params:Promise<{slug:string}>}) { const {slug} = await params; const service = services.find(s => s.slug === slug); const about = slug === 'nosotros'; if (!service && !about) notFound(); const items = service?.items ?? ['Entender el negocio antes de elegir una herramienta','Conectar estrategia, implementación y acompañamiento','Construir soluciones que puedan evolucionar']; return <><section className="container detail-hero"><Link className="breadcrumb" href="/">Inicio</Link><span className="breadcrumb"> / {service?.name ?? 'Nosotros'}</span><div className="detail-grid"><div><span className="eyebrow">{service?.tag ?? 'SOMOS DATALINK CORPORATION'}</span><h1>{service?.name ?? 'La tecnología conecta. Las personas la hacen posible.'}</h1><p>{service?.description ?? 'Creemos en una tecnología cercana, útil y alineada con lo que tu negocio necesita. DataLink reúne soluciones digitales e infraestructura bajo una misma visión: ayudarte a avanzar.'}</p><Link className="button button-lime" href="/contacto/">{about ? 'Conversemos' : 'Cuéntanos tu proyecto'}<ArrowUpRight size={18}/></Link></div><div className="detail-symbol"><Network size={130} strokeWidth={0.7}/><span>{service?.short ?? 'Tu visión. Nuestra conexión.'}</span></div></div></section><section className="container section detail-content"><div><span className="eyebrow">{about ? 'NUESTRA FORMA DE PENSAR' : 'CÓMO PODEMOS AYUDARTE'}</span><h2>{about ? 'Un aliado, de principio a fin.' : 'De la necesidad a la solución.'}</h2><p>Partimos de una conversación para entender tu situación, definir prioridades y proponer un alcance realista.</p></div><div className="feature-list">{items.map((item,i) => <div key={item}><span>0{i+1}</span><h3>{item}</h3><Check size={19}/></div>)}</div></section><CTA/></>; }
