import Link from 'next/link';
import { ArrowDown, ArrowUpRight, AudioLines, Check, Code2, Network, ShieldCheck, Sparkles } from 'lucide-react';
import { Reveal, ServiceCards } from '@/components/ui';
import { CTA } from '@/components/footer';
export default function Home() { return <>
 <section className="hero container"><div className="hero-copy"><div className="pill"><span className="status-dot"/> TU ALIADO EN TRANSFORMACIÓN DIGITAL</div><h1>Tecnología e IA<br/>para negocios<br/>que <span>avanzan.</span></h1><p>De una gran idea a una solución real. Integramos inteligencia artificial, software e infraestructura para llevar tu empresa al siguiente nivel.</p><div className="hero-actions"><Link className="button button-lime" href="/contacto/">Hablemos de tu proyecto <ArrowUpRight size={19}/></Link><a className="text-link" href="#soluciones">Explorar soluciones <ArrowDown size={16}/></a></div><div className="hero-caption"><span/> Una visión integral. Un solo aliado tecnológico.</div></div>
 <Reveal className="hero-visual"><div className="visual-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="connection-line line-one"/><div className="connection-line line-two"/><div className="core"><Network size={56} strokeWidth={1.2}/><strong>DataLink</strong><span>CONNECTED POSSIBILITIES</span></div><div className="floating-label label-ai"><Sparkles size={19}/><div>Inteligencia artificial<small>Ideas que evolucionan</small></div><span className="status-dot"/></div><div className="floating-label label-code"><Code2 size={19}/><div>Software a medida<small>Creado para tu negocio</small></div></div><div className="floating-label label-security"><ShieldCheck size={19}/><div>Infraestructura segura<small>Todo conectado</small></div></div><div className="visual-bottom"><AudioLines size={22}/><span>TECNOLOGÍA EN SINTONÍA<br/><strong>CON TU NEGOCIO</strong></span><span className="signal-bars">▂ ▄ ▆ █</span></div><div className="orbit-point p1"/><div className="orbit-point p2"/></Reveal></section>
 <div className="capabilities"><div className="container"><span>ESTRATEGIA + TECNOLOGÍA</span><p>Inteligencia artificial <i/> Desarrollo de software <i/> Infraestructura <i/> Crecimiento digital</p></div></div>
 <section className="container section" id="soluciones"><div className="section-heading"><div><span className="eyebrow">01 / NUESTRAS SOLUCIONES</span><h2>Todo lo que necesitas.<br/><span>Conectado en un solo lugar.</span></h2></div><p>Cada negocio tiene sus propios retos.<br/>Encuentra la tecnología que los transforma<br/>en nuevas oportunidades.</p></div><ServiceCards/></section>
 <section className="approach section" id="proceso"><div className="container"><div className="section-heading"><div><span className="eyebrow">02 / ASÍ LO HACEMOS POSIBLE</span><h2>Primero entendemos.<br/><span>Después, transformamos.</span></h2></div><Link className="text-link" href="/nosotros/">Conoce DataLink <ArrowUpRight size={17}/></Link></div><div className="steps">{[['01','Escuchamos tu reto','Conocemos tu negocio, tus procesos y hacia dónde quieres llegar.'],['02','Diseñamos la solución','Definimos una propuesta clara, con prioridades y un alcance compartido.'],['03','Lo hacemos realidad','Implementamos, validamos y te acompañamos en la puesta en marcha.']].map(([n,title,copy]) => <div key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="principles">{['Soluciones a tu medida','Comunicación clara','Visión a largo plazo'].map(p => <span key={p}><Check size={16}/>{p}</span>)}</div></div></section><CTA/>
 </>; }
